### ISSUE TITLE
Reason why the Svelte example performs poorly

### ISSUE THREAD

**Issue by antony** [bvisness/incremental#1]
Somebody posted this in the Svelte discord and I wanted to try to figure out why it was so slow. The first thing I noticed was that you've wrapped the entire `SearchResultMatch` in a reactive block, which will cause everything within it to recompute everything within it, on every change.

Simply dropping the `$: { }` results in vastly improved performance.

I've not got time to look any deeper right now but I can't help but feel that the performance issues are related to the way the example is written rather than a performance issue with Svelte itself (although I can't be 100% sure). I'll keep looking when I've got some time.

**Comment by antony** [comment]
I kept cracking on and I found a few changes which seem (I haven't measured), to make the Svelte example even faster than vanilla js.

1) if you also avoid using push and instead use `...` then you can make the Svelte version as fast as vanillla (by eye, I've not run any timings).
2) If you remove the reactive block and just use afterUpdate to trigger your highlighting
3) If you key all the each blocks (which other examples do)

```svelte
<script>
    import { afterUpdate } from 'svelte'
    export let result;
    export let match;

    let pieces = [];
    let startIndex = 0;

    afterUpdate(() => {
        pieces = []
        startIndex = 0
        for (const highlightMatch of match.text.matchAll(result.query)) {
            pieces = [ ...pieces, match.text.slice(startIndex, highlightMatch.index), highlightMatch[0] ]
            startIndex = highlightMatch.index + highlightMatch[0].length;
        }
        pieces = [ ...pieces, match.text.slice(startIndex) ]
    })

</script>

<p>
    {match.prettyTime}
    {#each pieces as piece, i (i)}
        {#if i % 2 === 0}
            {piece}
        {:else}
            <span class="highlight">{piece}</span>
        {/if}
    {/each}
</p>
```

**Comment by antony** [comment]
Oh and one more thing, I keyed all the `#each` blocks. This will result in faster performance, and parity with the React examples.

**Comment by bvisness** [comment]
Good to know, thanks. I'll have to patch that up and redo my timings. 

If you happen to see any stupid stuff in the Vue example too, please let me know! 😄 I'm experienced with React but new to Vue and Svelte.

**Comment by bvisness** [comment]
Ok, I took a look at your suggestions and unfortunately none of them seem to make much of a difference.

First of all, removing the `$: { }` just results in buggy behavior on updates. Furthermore, I don't understand why the reactive declaration would be updating more often than it needs to. Its only external dependencies are `result`, `match`, and `pieces`; `result` and `match` are props that should re-trigger the statement, and `pieces` is only assigned within the statement itself.

As for your other comments:

1. How would using `...` be faster than using `push` on an existing array? The only thing I can see that affecting is correctness of updates, since a `push` wouldn't reassign the variable and trigger an update - but I'm never modifying the array outside of this reactive declaration.
2. Why should I use `afterUpdate` to do my highlighting? The highlighting is part of the DOM and doesn't depend on computed positions or anything. Plus, I would expect changes made in `afterUpdate` to force another render - is that the case here? (I know that is the case in React, if I were to compute highlighting data in `componentDidUpdate` or `useEffect`.)
3. While I am glad to know how to use keys in Svelte (and I did indeed miss those when reading the docs), I really only care about mount times right now, and keys shouldn't have any meaningful impact on that. (Also, you used `i` as a loop key in your example, which surely doesn't do any good?)

And finally. I tried directly implementing your suggested code and measuring the results. I used the Chrome profiler to measure the total frame time when searching for "ab". I measured the Svelte code before and after your changes, and vanilla for comparison, and for each method I took five measurements and took the median.

method | individual measurements (ms) | median frame time (ms)
-- | -- | --
Vanilla (Naive) | 466 622 649 724 756 | 649
Svelte (Naive) (my current version) | 5700 5766 5783 5880 6699 | 5783
Svelte (Naive) (your proposed version) | 6049 6049 6183 6233 6349 | 6183

(Chrome 88.0.4324.104, Windows 10, i7-6700K 4.00GHz)

This isn't exactly beating vanilla, and in fact your changes made it worse.

**Comment by antony** [comment]
Interesting. I did definitely see 2-3 second results after my changes.

I'll re-test my branch and open a PR for you so you can review my exact changes, in case I missed something somewhere.

Apologies!

**Comment by bvisness** [comment]
I took a lot of measurements today. You can find them [here](https://github.com/bvisness/incremental/blob/master/timings/timings.ods) (in ODS spreadsheet format). Svelte is more middle of the pack in these timings.

However, in casual use (instead of the far more controlled methodology I used for measurement), I can still easily convince the Svelte version to take the longest time by far. My best guess is that it's because Svelte allocates the most memory of the three frameworks I tested, and on large enough tasks, that memory access becomes a bottleneck somewhere in the browser or the OS.

Here are some extremely casual memory stats to illustrate that (from typing "about" quickly in various methods). The absolute numbers don't matter as much as the ratios.

```
Heap size increase from performance tab (MB):
Vanilla (Naive):    10.3
React (Naive):      106.2
Vue (Naive):        273
Svelte (Naive):     305

Estimated browser mem usage from Task Manager (MB):
Vanilla (Naive):    563
React (Naive):      774
Vue (Naive):        1300
Svelte (Naive):     1989
```

I'm gonna close this issue because I'm basically done with this project; barring some obvious mistake in any of my implementations, I think these timings are representative for this test case and I'm happy with my results.
